name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install build-essential cmake npm mono-devel
    - uses: actions/checkout@v3
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.5.22307.18
        include-prerelease: true
    - name: Build UI
      run: cd src/ICUMonitor/UI && npm install && npm run build
    - name: Build WASM
      run: cd src/ICUMonitor && dotnet restore && dotnet build
    - name: Rename WASM
      run: cd src/ICUMonitor && mv bin/Debug/net7.0/ICUMonitor.wasm main.wasm
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: icu-wasm
        path: |
          src/ICUMonitor/main.wasm
          src/ICUMonitor/Enarx.toml
        if-no-files-found: error
